### Description
Explore Boston buildings data to identify potential attributes that could be 
used to eventually build an ML model or neural network.

Key Factors:
* Environmental
* Social
* Economic

Ethical Concerns: Consider that certain attributes may further socioeconomic
discrimination (redlining, food deserts, etc.).

### Data Source 
https://data.boston.gov/dataset/boston-buildings-inventory

### Label
`use_class`: building use classification

### Relevant Attributes
Note: The following attributes may not necessarily be used, but they were
considered to be relevant to the goals of this project.

Building Attributes: 
* `yr_built`: year built
* `sqft`: square feet
* `existing_ashp`: air-source heat pump installed
* `existing_gshp`: ground-source heat pump installed
* `existing_shw`: solar hot water system installed
* `historic_district`: located in a historic district
* `landmark`: located in a landmark district

Environmental Attributes: 
* `flood`: flood zone
* `stormwater`: stormwater flood zone

Social Attributes: 
* `ct_perc_children_under_5`: % of population under 5 years old
* `ct_perc_over_65`: % of population over 65 years old

In [2]:
import pandas as pd

In [3]:
FILENAME = "data/boston_buildings.csv"
LABEL = "use_class"
COLS = [LABEL, "yr_built", "sqft", "historic_district", "landmark", "flood", 
           "stormwater", "ct_perc_children_under_5", "ct_perc_over_65"]
BOOL_COLS = ["historic_district", "landmark", "flood", "stormwater"]

`existing_ashp`, `existing_gshp`, and `existing_shw` data was too sparse to
be usable attributes.

In [4]:
df = pd.read_csv(FILENAME)
df = df[COLS].dropna()
df

/var/folders/k8/3s73cc5x32b13wxlg0_xqlk80000gn/T/ipykernel_42566/1848298709.py:1: DtypeWarning: Columns (1,40,44,47,51,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(FILENAME)

,use_class,yr_built,sqft,historic_district,landmark,flood,stormwater,ct_perc_children_under_5,ct_perc_over_65
1,Residential,1940.0,1326.0,f,f,f,f,20.926988,9.145869
2,Residential,1875.0,1344.0,f,f,t,t,21.730217,16.892169
31,Residential,1865.0,1590.0,f,f,f,f,10.218978,13.029197
38,Commercial,1940.0,5332.0,f,f,f,f,30.579216,7.580920
112,Residential,2000.0,232116.0,f,t,f,f,7.878685,13.758048
...,...,...,...,...,...,...,...,...,...
98924,Residential,2007.0,1863.0,f,f,f,f,23.207269,11.738703
98925,Residential,2000.0,3140.0,f,f,f,f,10.828648,14.910780
98926,Residential,2005.0,2611.0,f,f,f,f,19.217745,17.660007
98927,Residential,2013.0,2129.0,f,f,f,f,10.218978,13.029197
98928,Residential,2009.0,4042.0,f,f,f,f,21.818650,6.671819

In [5]:
df[BOOL_COLS] = df[BOOL_COLS].replace({"f": 0, "t": 1})
df[BOOL_COLS]

/var/folders/k8/3s73cc5x32b13wxlg0_xqlk80000gn/T/ipykernel_42566/3196776862.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[BOOL_COLS] = df[BOOL_COLS].replace({"f": 0, "t": 1})

       historic_district  landmark  flood  stormwater
1                      0         0      0           0
2                      0         0      1           1
31                     0         0      0           0
38                     0         0      0           0
112                    0         1      0           0
...                  ...       ...    ...         ...
98924                  0         0      0           0
98925                  0         0      0           0
98926                  0         0      0           0
98927                  0         0      0           0
98928                  0         0      0           0

[84340 rows x 4 columns]

In [6]:
df

,use_class,yr_built,sqft,historic_district,landmark,flood,stormwater,ct_perc_children_under_5,ct_perc_over_65
1,Residential,1940.0,1326.0,0,0,0,0,20.926988,9.145869
2,Residential,1875.0,1344.0,0,0,1,1,21.730217,16.892169
31,Residential,1865.0,1590.0,0,0,0,0,10.218978,13.029197
38,Commercial,1940.0,5332.0,0,0,0,0,30.579216,7.580920
112,Residential,2000.0,232116.0,0,1,0,0,7.878685,13.758048
...,...,...,...,...,...,...,...,...,...
98924,Residential,2007.0,1863.0,0,0,0,0,23.207269,11.738703
98925,Residential,2000.0,3140.0,0,0,0,0,10.828648,14.910780
98926,Residential,2005.0,2611.0,0,0,0,0,19.217745,17.660007
98927,Residential,2013.0,2129.0,0,0,0,0,10.218978,13.029197
98928,Residential,2009.0,4042.0,0,0,0,0,21.818650,6.671819